enum WatchStatus {
  PLAN_TO_WATCH = 'PLAN_TO_WATCH',
  CURRENTLY_WATCHING = 'CURRENTLY_WATCHING',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
  ON_HOLD = 'ON_HOLD'
}
export default WatchStatus;
